---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linuxptp-service-account
  namespace: ptp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linuxptp-cluster-role
rules:
- apiGroups:
  - ""
  - k8s.cni.cncf.io
  resources:
  - nodes
  - pods
  - network-attachment-definitions
  verbs:
  - '*'
- apiGroups:
  - ptp.openshift.io
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linuxptp-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linuxptp-cluster-role
subjects:
- kind: ServiceAccount
  name: linuxptp-service-account
  namespace: ptp
